/* Auto-generated by zx0em_pack. Do not edit. */
#ifndef ZX0EM_INDEX_H
#define ZX0EM_INDEX_H

#include <stdint.h>

#define ZX0EM_MAX_PLANAR_SCRATCH_SIZE 0

/* Asset types */
/* Asset types */
#define ZX0EM_TYPE_IMAGE        0
#define ZX0EM_TYPE_TEXT_RAW     4
#define ZX0EM_TYPE_TEXT_BPE     5
#define ZX0EM_TYPE_FONT         6
#define ZX0EM_TYPE_BINARY       7

/* Pixel formats */
#define ZX0EM_PIXFMT_GRAY_ALPHA 0
#define ZX0EM_PIXFMT_PALETTE    1
#define ZX0EM_PIXFMT_RGBA       2
#define ZX0EM_PIXFMT_1BIT       3
#define ZX0EM_PIXFMT_NONE       7

typedef struct {
    const char *name;
    uint32_t    offset;
    uint32_t    size;
    uint16_t    width;
    uint16_t    height;
    uint8_t     type;      /* ZX0EM_TYPE_* */
    uint8_t     pixfmt;    /* ZX0EM_PIXFMT_* */
    uint8_t     palette_count;
    uint8_t     filters;   /* ZX0EM_FILTER_* */
    uint16_t    parent_id; /* MST parent index (0xFFFF if none) */
} zx0em_entry_t;

#define ZX0EM_ENTRY_COUNT 19

enum {
    ZX0EM_about_png = 0,
    ZX0EM_github_png = 1,
    ZX0EM_langue_png = 2,
    ZX0EM_help_png = 3,
    ZX0EM_secu_ok_png = 4,
    ZX0EM_home_png = 5,
    ZX0EM_opti_png = 6,
    ZX0EM_parameters_png = 7,
    ZX0EM_policies_png = 8,
    ZX0EM_profil_png = 9,
    ZX0EM_role_png = 10,
    ZX0EM_tuneperfs_png = 11,
    ZX0EM_konqi_perfs_png = 12,
    ZX0EM_de_txt = 13,
    ZX0EM_en_txt = 14,
    ZX0EM_es_txt = 15,
    ZX0EM_fr_txt = 16,
    ZX0EM_it_txt = 17,
    ZX0EM_pl_txt = 18,
    ZX0EM__COUNT = 19
};

static const zx0em_entry_t zx0em_entries[ZX0EM_ENTRY_COUNT] = {
    { "about.png", 0U, 593U, 24, 24, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 4, 0x00, 0xFFFF },
    { "github.png", 593U, 597U, 24, 24, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "langue.png", 1190U, 597U, 24, 24, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "help.png", 1787U, 1069U, 32, 32, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 11, 0x00, 0xFFFF },
    { "secu_ok.png", 2856U, 1053U, 32, 32, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 7, 0x00, 0xFFFF },
    { "home.png", 3909U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "opti.png", 8026U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "parameters.png", 12143U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "policies.png", 16260U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "profil.png", 20377U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "role.png", 24494U, 4117U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 5, 0x00, 0xFFFF },
    { "tuneperfs.png", 28611U, 4137U, 64, 64, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 10, 0x00, 0xFFFF },
    { "konqi_perfs.png", 32748U, 41441U, 200, 207, ZX0EM_TYPE_IMAGE, ZX0EM_PIXFMT_PALETTE, 10, 0x00, 0xFFFF },
    { "de.txt", 74189U, 22894U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
    { "en.txt", 97083U, 20009U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
    { "es.txt", 117092U, 21751U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
    { "fr.txt", 138843U, 22632U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
    { "it.txt", 161475U, 20830U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
    { "pl.txt", 182305U, 24122U, 0, 0, ZX0EM_TYPE_TEXT_BPE, ZX0EM_PIXFMT_NONE, 0, 0x00, 0xFFFF },
};

/* Direct access macros */
#define ZX0EM_about_png_OFFSET 0U
#define ZX0EM_about_png_SIZE   593U
#define ZX0EM_about_png_W      24
#define ZX0EM_about_png_H      24

#define ZX0EM_github_png_OFFSET 593U
#define ZX0EM_github_png_SIZE   597U
#define ZX0EM_github_png_W      24
#define ZX0EM_github_png_H      24

#define ZX0EM_langue_png_OFFSET 1190U
#define ZX0EM_langue_png_SIZE   597U
#define ZX0EM_langue_png_W      24
#define ZX0EM_langue_png_H      24

#define ZX0EM_help_png_OFFSET 1787U
#define ZX0EM_help_png_SIZE   1069U
#define ZX0EM_help_png_W      32
#define ZX0EM_help_png_H      32

#define ZX0EM_secu_ok_png_OFFSET 2856U
#define ZX0EM_secu_ok_png_SIZE   1053U
#define ZX0EM_secu_ok_png_W      32
#define ZX0EM_secu_ok_png_H      32

#define ZX0EM_home_png_OFFSET 3909U
#define ZX0EM_home_png_SIZE   4117U
#define ZX0EM_home_png_W      64
#define ZX0EM_home_png_H      64

#define ZX0EM_opti_png_OFFSET 8026U
#define ZX0EM_opti_png_SIZE   4117U
#define ZX0EM_opti_png_W      64
#define ZX0EM_opti_png_H      64

#define ZX0EM_parameters_png_OFFSET 12143U
#define ZX0EM_parameters_png_SIZE   4117U
#define ZX0EM_parameters_png_W      64
#define ZX0EM_parameters_png_H      64

#define ZX0EM_policies_png_OFFSET 16260U
#define ZX0EM_policies_png_SIZE   4117U
#define ZX0EM_policies_png_W      64
#define ZX0EM_policies_png_H      64

#define ZX0EM_profil_png_OFFSET 20377U
#define ZX0EM_profil_png_SIZE   4117U
#define ZX0EM_profil_png_W      64
#define ZX0EM_profil_png_H      64

#define ZX0EM_role_png_OFFSET 24494U
#define ZX0EM_role_png_SIZE   4117U
#define ZX0EM_role_png_W      64
#define ZX0EM_role_png_H      64

#define ZX0EM_tuneperfs_png_OFFSET 28611U
#define ZX0EM_tuneperfs_png_SIZE   4137U
#define ZX0EM_tuneperfs_png_W      64
#define ZX0EM_tuneperfs_png_H      64

#define ZX0EM_konqi_perfs_png_OFFSET 32748U
#define ZX0EM_konqi_perfs_png_SIZE   41441U
#define ZX0EM_konqi_perfs_png_W      200
#define ZX0EM_konqi_perfs_png_H      207

#define ZX0EM_de_txt_OFFSET 74189U
#define ZX0EM_de_txt_SIZE   22894U

#define ZX0EM_en_txt_OFFSET 97083U
#define ZX0EM_en_txt_SIZE   20009U

#define ZX0EM_es_txt_OFFSET 117092U
#define ZX0EM_es_txt_SIZE   21751U

#define ZX0EM_fr_txt_OFFSET 138843U
#define ZX0EM_fr_txt_SIZE   22632U

#define ZX0EM_it_txt_OFFSET 161475U
#define ZX0EM_it_txt_SIZE   20830U

#define ZX0EM_pl_txt_OFFSET 182305U
#define ZX0EM_pl_txt_SIZE   24122U

#endif /* ZX0EM_INDEX_H */
