/* Auto-generated by zx0em_pack. Do not edit. */
#ifndef ZX0EM_BLOB_DATA_H
#define ZX0EM_BLOB_DATA_H

#define ZX0EM_UNCOMPRESSED_SIZE 206427U
#define ZX0EM_COMPRESSED_SIZE   90127U

extern const unsigned char zx0em_blob_z[ZX0EM_COMPRESSED_SIZE];

#endif /* ZX0EM_BLOB_DATA_H */
