/* Auto-generated by zx0em_pack. Do not edit. */
/*
 * zx0em_runtime.h - Standalone runtime API for embedded assets
 *
 * No dependency on libpng, tqt3, or any framework.
 * Images are raw pixels ready for direct use.
 * Include this header + zx0em_blob_data.c in your project.
 * You also need the ZX0 decompressor (~95 lines of C).
 */
#ifndef ZX0EM_RUNTIME_H
#define ZX0EM_RUNTIME_H

#include "zx0em_index.h"
#include "zx0em_blob_data.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ZX0 decompressor (include zx0_decompress.c in your build) */
int zx0_decompress_to(const unsigned char *in, int in_size,
                      unsigned char *out, int out_max);

extern unsigned char zx0em_buf_[ZX0EM_UNCOMPRESSED_SIZE];
extern int zx0em_inited_;

#if ZX0EM_MAX_PLANAR_SCRATCH_SIZE > 0
extern unsigned char _zx0em_planar_scratch[ZX0EM_MAX_PLANAR_SCRATCH_SIZE];
#else
extern unsigned char _zx0em_planar_scratch[1];
#endif

static inline unsigned char paeth_predict(unsigned char a, unsigned char b, unsigned char c) {
    int p = (int)a + (int)b - (int)c;
    int pa = p > (int)a ? p - (int)a : (int)a - p;
    int pb = p > (int)b ? p - (int)b : (int)b - p;
    int pc = p > (int)c ? p - (int)c : (int)c - p;
    if (pa <= pb && pa <= pc) return a;
    if (pb <= pc) return b;
    return c;
}

/* Initialize: decompress the blob. Call once at startup.
 * Returns 1 on success, 0 on failure. */
static inline int zx0em_init(void) {
    if (zx0em_inited_) return 1;
    int n = zx0_decompress_to(zx0em_blob_z, (int)ZX0EM_COMPRESSED_SIZE,
                              zx0em_buf_, (int)ZX0EM_UNCOMPRESSED_SIZE);
    if (n != (int)ZX0EM_UNCOMPRESSED_SIZE) return 0;
    /* Undo DELTA / XOR in-place */
    for (int i = 0; i < ZX0EM_ENTRY_COUNT; i++) {
        const zx0em_entry_t *e = &zx0em_entries[i];
        if (e->type != ZX0EM_TYPE_IMAGE || e->filters == 0) continue;
        int bpp = 1;
        if (e->pixfmt == ZX0EM_PIXFMT_GRAY_ALPHA) bpp = 2;
        else if (e->pixfmt == ZX0EM_PIXFMT_RGBA) bpp = 4;
        unsigned int pitch = 0;
        if (e->pixfmt == ZX0EM_PIXFMT_RGBA) pitch = (unsigned int)e->width * 4;
        else if (e->pixfmt == ZX0EM_PIXFMT_GRAY_ALPHA) pitch = (unsigned int)e->width * 2;
        else if (e->pixfmt == ZX0EM_PIXFMT_PALETTE) pitch = (unsigned int)e->width * 1;
        else if (e->pixfmt == ZX0EM_PIXFMT_1BIT) pitch = ((unsigned int)e->width + 7) / 8;
        unsigned int pal_size = 0;
        if (e->pixfmt == ZX0EM_PIXFMT_PALETTE && e->palette_count > 0)
            pal_size = 1 + (unsigned int)e->palette_count * 4;
        unsigned char *data = &zx0em_buf_[e->offset + pal_size];
        unsigned int size = e->size - pal_size;
        unsigned char spatial = e->filters & 0x0F;
        unsigned char inter   = e->filters & 0xF0;
        /* 1. Reverse Spatial Filter */
        if (spatial == 1) { /* LEFT XOR */
            for (unsigned int k = (unsigned int)bpp; k < size; k++) data[k] ^= data[k - bpp];
        } else if (spatial == 2) { /* LEFT SUB */
            for (unsigned int k = (unsigned int)bpp; k < size; k++) data[k] = (unsigned char)(data[k] + data[k - bpp]);
        } else if (spatial == 3) { /* UP XOR */
            for (unsigned int k = pitch; k < size; k++) data[k] ^= data[k - pitch];
        } else if (spatial == 4) { /* UP SUB */
            for (unsigned int k = pitch; k < size; k++) data[k] = (unsigned char)(data[k] + data[k - pitch]);
        } else if (spatial == 5) { /* PLANAR (GRAY_ALPHA: GGG..AAA.. -> GAGAGA) */
            unsigned int half = size / 2;
            /* Save alpha channel (second half) */
            for (unsigned int k = 0; k < half; k++)
                _zx0em_planar_scratch[k] = data[half + k];
            /* Spread gray values backward: pos i -> pos 2*i */
            for (int k = (int)half - 1; k >= 1; k--)
                data[k * 2] = data[k];
            /* Interleave alpha from scratch */
            for (unsigned int k = 0; k < half; k++)
                data[k * 2 + 1] = _zx0em_planar_scratch[k];
        } else if (spatial == 6) { /* PLANAR RGBA (RRR...GGG...BBB...AAA... -> RGBA RGBA...) */
            unsigned int plane_sz = size / 4;
            /* Save G, B, A channels in scratch */
            for (unsigned int k = 0; k < plane_sz * 3; k++)
                _zx0em_planar_scratch[k] = data[plane_sz + k];
            /* Spread R values backward: pos i -> pos 4*i */
            for (int k = (int)plane_sz - 1; k >= 0; k--)
                data[k * 4] = data[k];
            /* Interleave G, B, A from scratch */
            for (unsigned int k = 0; k < plane_sz; k++) {
                data[k * 4 + 1] = _zx0em_planar_scratch[k];
                data[k * 4 + 2] = _zx0em_planar_scratch[plane_sz + k];
                data[k * 4 + 3] = _zx0em_planar_scratch[plane_sz * 2 + k];
            }
        } else if (spatial == 7) { /* AVG XOR */
            unsigned int px = 0, chan = 0;
            for (unsigned int k = 0; k < size; k++) {
                unsigned char left = (px > 0) ? data[k - bpp] : 0;
                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;
                data[k] ^= (unsigned char)(((int)left + (int)up) / 2);
                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }
            }
        } else if (spatial == 8) { /* AVG SUB */
            unsigned int px = 0, chan = 0;
            for (unsigned int k = 0; k < size; k++) {
                unsigned char left = (px > 0) ? data[k - bpp] : 0;
                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;
                data[k] = (unsigned char)(data[k] + (((int)left + (int)up) / 2));
                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }
            }
        } else if (spatial == 9) { /* PAETH XOR */
            unsigned int px = 0, chan = 0;
            for (unsigned int k = 0; k < size; k++) {
                unsigned char left = (px > 0) ? data[k - bpp] : 0;
                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;
                unsigned char left_up = (px > 0 && k >= pitch) ? data[k - pitch - bpp] : 0;
                data[k] ^= paeth_predict(left, up, left_up);
                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }
            }
        } else if (spatial == 10) { /* PAETH SUB */
            unsigned int px = 0, chan = 0;
            for (unsigned int k = 0; k < size; k++) {
                unsigned char left = (px > 0) ? data[k - bpp] : 0;
                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;
                unsigned char left_up = (px > 0 && k >= pitch) ? data[k - pitch - bpp] : 0;
                data[k] = (unsigned char)(data[k] + paeth_predict(left, up, left_up));
                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }
            }
        } else if (spatial >= 11 && spatial <= 16) { /* CHAINED: secondary spatial + PLANAR */
            /* Step 1: Undo secondary spatial filter (bpp=1, planar pitch=width) */
            unsigned int pl_pitch = e->width;
            int sec = 0;
            if (spatial == 11 || spatial == 14) sec = 1;  /* LEFT_XOR */
            else if (spatial == 12 || spatial == 15) sec = 3; /* UP_XOR */
            else if (spatial == 13 || spatial == 16) sec = 10; /* PAETH_SUB */
            if (sec == 1) {
                for (unsigned int k = 1; k < size; k++) data[k] ^= data[k - 1];
            } else if (sec == 3) {
                for (unsigned int k = pl_pitch; k < size; k++) data[k] ^= data[k - pl_pitch];
            } else if (sec == 10) {
                unsigned int px2 = 0, chan2 = 0;
                for (unsigned int k = 0; k < size; k++) {
                    unsigned char left = (px2 > 0) ? data[k - 1] : 0;
                    unsigned char up = (k >= pl_pitch) ? data[k - pl_pitch] : 0;
                    unsigned char left_up = (px2 > 0 && k >= pl_pitch) ? data[k - pl_pitch - 1] : 0;
                    data[k] = (unsigned char)(data[k] + paeth_predict(left, up, left_up));
                    chan2++; if (chan2 == 1) { chan2 = 0; px2++; if (px2 == e->width) px2 = 0; }
                }
            }
            /* Step 2: Undo PLANAR de-interleave */
            if (spatial <= 13) { /* PLANAR GA */
                unsigned int half = size / 2;
                for (unsigned int k = 0; k < half; k++)
                    _zx0em_planar_scratch[k] = data[half + k];
                for (int k = (int)half - 1; k >= 1; k--)
                    data[k * 2] = data[k];
                for (unsigned int k = 0; k < half; k++)
                    data[k * 2 + 1] = _zx0em_planar_scratch[k];
            } else { /* PLANAR RGBA */
                unsigned int plane_sz = size / 4;
                for (unsigned int k = 0; k < plane_sz * 3; k++)
                    _zx0em_planar_scratch[k] = data[plane_sz + k];
                for (int k = (int)plane_sz - 1; k >= 0; k--)
                    data[k * 4] = data[k];
                for (unsigned int k = 0; k < plane_sz; k++) {
                    data[k * 4 + 1] = _zx0em_planar_scratch[k];
                    data[k * 4 + 2] = _zx0em_planar_scratch[plane_sz + k];
                    data[k * 4 + 3] = _zx0em_planar_scratch[plane_sz * 2 + k];
                }
            }
        }
        /* 2. Reverse Inter-image Filter */
        if (inter != 0 && e->parent_id != 0xFFFF) {
            const zx0em_entry_t *parent = &zx0em_entries[e->parent_id];
            unsigned int p_pal_size = 0;
            if (parent->pixfmt == ZX0EM_PIXFMT_PALETTE && parent->palette_count > 0)
                p_pal_size = 1 + (unsigned int)parent->palette_count * 4;
            unsigned char *parent_data = &zx0em_buf_[parent->offset + p_pal_size];
            if (inter == 0x10) { /* INTER XOR */
                for (unsigned int k = 0; k < size; k++) data[k] ^= parent_data[k];
            } else if (inter == 0x20) { /* INTER SUB */
                for (unsigned int k = 0; k < size; k++) data[k] = (unsigned char)(data[k] + parent_data[k]);
            }
        }
    }
    zx0em_inited_ = 1;
    return 1;
}

/* Get raw asset data by ID. Returns NULL on error.
 * Sets *size to the asset size in bytes. */
static inline const unsigned char* zx0em_get(int id, unsigned int *size) {
    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;
    const zx0em_entry_t *e = &zx0em_entries[id];
    if (size) *size = e->size;
    return &zx0em_buf_[e->offset];
}

/* Get image asset with dimensions and pixel format.
 * Returns pointer to raw pixel data, or NULL. */
static inline const unsigned char* zx0em_get_image(
        int id, int *w, int *h, int *pixfmt) {
    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;
    const zx0em_entry_t *e = &zx0em_entries[id];
    if (e->type != ZX0EM_TYPE_IMAGE) return 0; /* not an image */
    if (w) *w = e->width;
    if (h) *h = e->height;
    if (pixfmt) *pixfmt = e->pixfmt;
    return &zx0em_buf_[e->offset];
}

/* Get text asset. Returns pointer to text data, or NULL. */
static inline const unsigned char* zx0em_get_text(
        int id, unsigned int *len) {
    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;
    const zx0em_entry_t *e = &zx0em_entries[id];
    if (e->type != ZX0EM_TYPE_TEXT_RAW && e->type != ZX0EM_TYPE_TEXT_BPE)
        return 0;
    if (len) *len = e->size;
    return &zx0em_buf_[e->offset];
}

/* Helper to recursively expand BPE tokens */
static inline void _zx0em_bpe_expand(unsigned char c, const unsigned char *dict, int dict_count, char *out_buf, int *out_len, int max_len) {
    if (*out_len >= max_len - 1) return;
    int found = 0;
    for (int j = 0; j < dict_count; j++) {
        if (dict[j * 3] == c) {
            _zx0em_bpe_expand(dict[j * 3 + 1], dict, dict_count, out_buf, out_len, max_len);
            _zx0em_bpe_expand(dict[j * 3 + 2], dict, dict_count, out_buf, out_len, max_len);
            found = 1;
            break;
        }
    }
    if (!found) {
        out_buf[(*out_len)++] = (char)c;
    }
}

/* Decode BPE text. Requires user-provided buffer. */
static inline int zx0em_decode_bpe(int id, char *out_buf, int max_len) {
    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return -1;
    const zx0em_entry_t *e = &zx0em_entries[id];
    if (e->type != ZX0EM_TYPE_TEXT_BPE) {
        /* Not BPE, just copy */
        int cplen = e->size < (unsigned int)max_len ? (int)e->size : max_len - 1;
        for (int i=0; i<cplen; i++) out_buf[i] = (char)zx0em_buf_[e->offset + i];
        out_buf[cplen] = '\0';
        return cplen;
    }
    const unsigned char *p = &zx0em_buf_[e->offset];
    int dict_count = *p++;
    const unsigned char *dict = p;
    p += dict_count * 3;
    int in_len = e->size - 1 - dict_count * 3;
    int out_len = 0;
    for (int i = 0; i < in_len && out_len < max_len - 1; i++) {
        _zx0em_bpe_expand(p[i], dict, dict_count, out_buf, &out_len, max_len);
    }
    out_buf[out_len] = '\0';
    return out_len;
}

/* Get asset name by ID */
static inline const char* zx0em_name(int id) {
    if (id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;
    return zx0em_entries[id].name;
}

#ifdef __cplusplus
}
#endif

#endif /* ZX0EM_RUNTIME_H */
